apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bohem-tudosjatek
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FELHASZNALONEV/bohem-tudosjatek-k8s.git
    targetRevision: HEAD
    path: bohem-tudosjatek
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true